[workspace]
members = ["build", "core", "macro"]
resolver = "3"

[workspace.package]
version = "0.1.1"
edition = "2024"
rust-version = "1.88"
license = "MIT"
readme = "README.md"
keywords = ["css", "css-modules", "topcoat", "web"]
categories = ["web-programming", "development-tools::build-utils"]

[workspace.dependencies]
proc-macro2 = { version = "1.0.107", features = ["span-locations"] }
quote = "1.0.47"
syn = { version = "3.0.5", features = ["full"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
topcoat-css-core = { path = "core" }
topcoat-css-macro = { path = "macro" }

[package]
name = "topcoat-css"
description = "Local CSS modules & macro for Topcoat Web Framework"
documentation = "https://docs.rs/topcoat-css"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
include = ["src/**", "Cargo.toml", "README.md", "LICENSE.md"]

[dependencies]
topcoat-css-macro.workspace = true

[dev-dependencies]
tempfile = "3.27.0"
