[package]
name = "topcoat-css-macro"
description = "Procedural macros for topcoat-css"
documentation = "https://docs.rs/topcoat-css-macro"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
include = ["src/**", "Cargo.toml", "README.md", "LICENSE.md"]

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
serde_json.workspace = true
topcoat-css-core = { workspace = true, features = ["compiler"] }

[dev-dependencies]
tempfile = "3.27.0"
